# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: grafana-db-secret
stringData:
  GF_DATASOURCE_HOUSE_DB_PASSWORD: ENC[AES256_GCM,data:mbG47uJ4NYz83H4xUsiwuOOdNWk5rMop58lY2HKSJyI=,iv:td3LCYgsvvq9LfxJOoEnu5ihlz79yGJP0qVIaifJrKI=,tag:s1kmynGFssmoA2tAZS1WGw==,type:str]
sops:
  age:
    - recipient: age1z6d3zhnz20zftekvmeuvygfjwsssua7tgtu00tt24uksvkpl9qdqr9ljqe
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzeVp4dms3d2hJNXJyUW8x
        R0tUY2NMTDd2aDQ3SkdhYXNmT1lSK0JFYnp3Cm90YjZ4cXZhVVhvZ0ZDMndpbTBE
        U2JtNVNneGg2eHJmMkJORlUwUnVmeUkKLS0tIG9Xa29pZVY4N0RucFJNYWtYVWl4
        ZitkS0NzVExtVWZmZWcycnd0S2trNW8KjgiGXW1nH40TJctxzTSKYOLuiKlUktFE
        ebtIBZ4uJVVTWNKnYaTtrUdxv1AOplDIL+zO+U8OL2WwPe3AUHlTpg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-07-11T04:35:32Z"
  mac: ENC[AES256_GCM,data:wuXn/tS1G4yZXNmsdnLZ85WoFQLk4tmltX+tH1yzg8Dt9GsSASDFaK5jLPXuTi78C7TFgg4/N08Rt/sHiXKCfTRhfwayMqpbyoAmGtB/zyr1OICo3rYsXf4IQrZUFXPlk4PTV47ebxmtD9srvkv9avytvgW+8ky20uqJVs/71/s=,iv:bTH/VmtDJVTqgXK2n9XaE3OLpKXq/pgg23JOOJ84xao=,tag:3R7cJJ59x9FyHV6zyszkeg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
