---
creation_rules:
  - path_regex: talsecret.sops.yaml
    mac_only_encrypted: true
    age: age1z6d3zhnz20zftekvmeuvygfjwsssua7tgtu00tt24uksvkpl9qdqr9ljqe
  - path_regex: (apps|components)/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    mac_only_encrypted: true
    age: age1z6d3zhnz20zftekvmeuvygfjwsssua7tgtu00tt24uksvkpl9qdqr9ljqe
stores:
  yaml:
    indent: 2

