clusterName: house
endpoint: https://192.168.1.200:6443
allowSchedulingOnMasters: true
allowSchedulingOnControlPlanes: true
additionalMachineCertSans:
  - 192.168.1.200
additionalApiServerCertSans:
  - house.local
cniConfig:
   name: none
nodes:
    - hostname: k8s-4
      controlPlane: true
      ipAddress: 192.168.1.21
      machineSpec:
        mode: metal
        arch: amd64
        secureboot: true
        useUKI: true
      networkInterfaces:
        - deviceSelector:
            physical: true
          dhcp: true
          vip:
            ip: 192.168.1.200
      installDisk: /dev/nvme0n1
      userVolumes:
        - name: openebs
          provisioning:
            diskSelector:
              match: disk.transport == "nvme"
            maxSize: "200GiB"
          filesystem:
            type: xfs
      kernelModules:
        - name: zfs
      volumes:
        - name: EPHEMERAL
          provisioning:
            diskSelector:
              match: disk.transport == "nvme"
            maxSize: 50GiB
        - name: IMAGECACHE
          provisioning:
            diskSelector:
              match: disk.transport == "nvme"
            maxSize: 50GiB
      patches:
        - "@./patches/local-path.yaml"
      schematic:
        customization:
          extraKernelArgs:
            - net.ifnames=0
            - amd_pstate=active
            - mitigations=off
            - iommu.passthrough=1
          systemExtensions:
            officialExtensions:
              - siderolabs/amd-ucode
              - siderolabs/amdgpu
              - siderolabs/zfs
   #- hostname: k8s-3
   #  controlPlane: false
   #  ipAddress: 192.168.1.165
   #  installDisk: /dev/sda
   #  schematic:
   #    overlay:
   #      name: rpi_generic
   #      image: siderolabs/sbc-raspberrypi
controlPlane:
  patches:
    - "@./patches/controller/cluster-config.yaml"
  


