version: 3
includes:
  bootstrap: .taskfiles/bootstrap
  cnpg: .taskfiles/cnpg
  factorio: .taskfiles/factorio
  grafana: .taskfiles/grafana
  homeassistant: .taskfiles/homeassistant
  talos: .taskfiles/talos
  volsync: .taskfiles/volsync
tasks:
  default: task --list