apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "${CLAIM}"
spec:
  accessModes:
    - ${ACCESS_MODE:-ReadWriteOnce}
  dataSourceRef:
    apiGroup: volsync.backube
    kind: ReplicationDestination
    name: "${CLAIM}-restore"
  resources:
    requests:
      storage: ${CAPACITY:-1Gi}
  storageClassName: host-zfs-standard
