---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: "${CLAIM}-backup"
spec:
  # The PVC to be backed up
  sourcePVC: "${CLAIM}"
  trigger:
    schedule: "0 */4 * * *"
  restic:
    # Prune the repository (repack to free space) every 2 weeks
    pruneIntervalDays: 14
    # Name of the Secret with the connection information
    repository: ${CLAIM}-backup-config
    # Retention policy for backups
    retain:
      hourly: 24
      daily: 30
    # Clone the source volume prior to taking a backup to ensure a
    # point-in-time image.
    copyMethod: Snapshot
    # The StorageClass to use when creating the PiT copy (same as source PVC if omitted)
    storageClassName: host-zfs-standard
    # The VSC to use if the copy method is Snapshot (default if omitted)
    volumeSnapshotClassName: host-zfs-snapshot
    moverSecurityContext:
      runAsUser: ${VOLSYNC_PUID:=1000}
      runAsGroup: ${VOLSYNC_PGID:=1000}
      fsGroup: ${VOLSYNC_PGID:=1000}