apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: "${CLAIM}-restore"
spec:
  trigger:
    manual: restore-once
  restic:
    repository: ${CLAIM}-backup-config
    copyMethod: Snapshot
    volumeSnapshotClassName: openebs-lvm
    storageClassName: openebs-lvm
    # these should match the restored PVC
    accessModes: ["ReadWriteOnce"]
    capacity: ${CAPACITY:-1Gi}
