apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: "${CLAIM}-restore"
spec:
  trigger:
    manual: restore-once
  restic:
    repository: ${CLAIM}-backup-config
    copyMethod: Snapshot
    volumeSnapshotClassName: topolvm-provisioner
    storageClassName: topolvm-provisioner
    # these should match the restored PVC
    accessModes: ["ReadWriteOnce"]
    capacity: ${CAPACITY:-1Gi}
    moverSecurityContext:
      runAsUser: ${VOLSYNC_PUID:=1000}
      runAsGroup: ${VOLSYNC_PGID:=1000}
      fsGroup: ${VOLSYNC_PGID:=1000}
