---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app media
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      media:
        annotations:
          reloader.stakater.com/auto: "true"
          zzzk8s.v1.cni.cncf.io/networks: |
            [{
                "name": "house",
                "namespace": "network",
                "ips": ["192.168.1.4/24"]
            }]
        containers:
          *app :
            image:
              repository: itsthenetwork/nfs-server-alpine
              tag: 12
            env:
              TZ: ${SECRET_TZ}
              SHARED_DIRECTORY: /media
            probes:
              readiness: &probes
                enabled: true
                custom: true
                spec:
                  exec:
                    command:
                      - sh
                      - -c
                      - "showmount -e localhost | grep -q \"$SHARED_DIRECTORY\""
              liveness: *probes
            securityContext:
              allowPrivilegeEscalation: true
              readOnlyRootFilesystem: false
              privileged: true
              #capabilities: { add: ["SYS_ADMIN", "SETPCAP"] }
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 1Gi
    service:
      server:
        controller: *app
        clusterIP: 192.168.1.4
        ports:
          nfs:
            port: 2049
            protocol: TCP
    persistence:
      media:
        existingClaim: media
        globalMounts:
          - path: /media