---
apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: house-db-server-ca
spec:
  sources:
    - useDefaultCAs: true
  target:
    secret:
      key: ca.crt
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: default
