---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: house-db
spec:
  enableSuperuserAccess: true
  instances: 3
  primaryUpdateStrategy: unsupervised
  storage:
    size: 10Gi
    storageClass: host-zfs-postgres
  postgresql:
    parameters:
      max_connections: "100"
      shared_buffers: 256MB
  bootstrap:
    initdb:
      database: app
      owner: app
      postInitApplicationSQL:
        - GRANT CONNECT ON DATABASE app TO grafana
        - GRANT USAGE ON SCHEMA public TO grafana
        - GRANT SELECT ON ALL TABLES IN SCHEMA public TO grafana
        - ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO grafana
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: house-db
  certificates:
    serverTLSSecret: house-db-server-cert
    serverCASecret: house-db-server-ca
  managed:
    roles:
      - name: grafana
        ensure: present
        login: true
        superuser: false
        createdb: false
        createrole: false
        inherit: true
        passwordSecret:
          name: grafana-db-secret
  monitoring:
    enablePodMonitor: false
