---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: house-db
spec:
  instances: 3
  primaryUpdateStrategy: unsupervised
  storage:
    size: 10Gi
    storageClass: host-zfs-standard
  postgresql:
    parameters:
      max_connections: "100"
      shared_buffers: 256MB
  monitoring:
    enablePodMonitor: false
