---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: house-db
spec:
  enableSuperuserAccess: true
  instances: 3
  primaryUpdateStrategy: unsupervised
  storage:
    size: 10Gi
    storageClass: host-zfs-standard
  postgresql:
    parameters:
      max_connections: "100"
      shared_buffers: 256MB
  bootstrap:
    initdb:
      database: app
      owner: app
      postInitApplicationSQL: []
  backup:
    barmanObjectStore:
      destinationPath: s3://hef-restic/cnpg/house-db
      endpointURL: https://s3.us-west-004.backblazeb2.com
      s3Credentials:
        accessKeyId:
          name: house-db-backup-creds
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: house-db-backup-creds
          key: ACCESS_SECRET_KEY
      wal:
        compression: gzip
      data:
        compression: gzip
    retentionPolicy: "30d"
  certificates:
    serverTLSSecret: house-db-server-cert
  monitoring:
    enablePodMonitor: false
