---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: immich
spec:
  name: immich
  owner: immich
  ensure: present
  databaseReclaimPolicy: retain
  encoding: UTF8
  localeCollate: C
  localeCType: C
  cluster:
    name: house-db
  extensions:
    - name: vector
      ensure: present
    - name: vchord
      ensure: present
    - name: cube
      ensure: present
    - name: earthdistance
      ensure: present
    - name: unaccent
      ensure: present
    - name: pg_trgm
      ensure: present
