# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: grafana-db-secret
stringData:
  username: ENC[AES256_GCM,data:Suwtjt5pbQ==,iv:MML6beQOhdwLZ1uUTl3tjVXnHCEpwv3lwSjnFJYLZgg=,tag:lgIMXh6+qajn9QzhmN7dfQ==,type:str]
  password: ENC[AES256_GCM,data:+qhxVyHQKtIpzicRazxkHbPEHjkhRDaF1cOqmdGc/Io=,iv:gXSQF1Pw2ua9bTWYb24YMfYUBJNvjs9ZRIfJ2VqURv8=,tag:lL9ACRK9kE2SbsotBD18tQ==,type:str]
sops:
  age:
    - recipient: age1z6d3zhnz20zftekvmeuvygfjwsssua7tgtu00tt24uksvkpl9qdqr9ljqe
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3TWNFUkZSY0VZRE53K3c1
        YzNWSzRqQVpYRDFiWTFuY1kwY2p4TVFlSzNJCkU0aURVS0pwNGViT011MUpGMGYv
        bHFkczZ2bUphaTBHaW5HWDJzWVIzYmsKLS0tIDVGV3ozanRpL3hOd3lhYkdsZUs0
        Q1NRclRvNElqSEYxeXNVUm5uclRkY1kKk/octHRNTOdC36QCNZ5ADnUhZmvx9D+E
        sgherLFo9JWfOJJJZhkSe+PlFJY2dlrFUrKEISSwXb8SdxIZ4XU8hg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-07-11T04:34:40Z"
  mac: ENC[AES256_GCM,data:EOWYGArTbNmAGaj/wslj4HcpcY4lJOlfLWMs30XGai5Nu87XRqcSFy0UoFvh1yl1G9syL+aJI82TRzlJzK7OBDMMpD6ImLVJFK/phV8lUv6WBiQsyA9lzz07wymPpkcKuS9+2VDARTXVvTOW5O87XSVcBN0bqjbyvQ0VckG2XwA=,iv:3rEKNqAod8QkJrC7DA+C1OwymcDbbjjkChKNZJZogHI=,tag:cDV2i1eitXyhl9I49caLtQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
