# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: immich-db-secret
stringData:
  username: ENC[AES256_GCM,data:vfP/GZbk,iv:pAH9bNuHF0PA0XOi5Q2NF326/Bby3oL9XjSBKlJZNp4=,tag:AM6ldsAPSGefJMHVr1Unxw==,type:str]
  dbname: ENC[AES256_GCM,data:qSGFBNOi,iv:cIhTyDnr4vJHCLkhV/c+GTna8I9oVaou6ApSnTcLxE0=,tag:zPkvjPx+mOMrzbjjPLiNDw==,type:str]
  password: ENC[AES256_GCM,data:idD7vJfiisJ517O25uyBJZFKnJqYGvDtmUnOnLkwjBE=,iv:yyBsBB9NwjM9kuGnJ2+AmMiMOCl4a4MNN6DF7QMeZdM=,tag:lVuUS2gP3HRIYmFtRKDTqQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByTEdPT1JzejA2ckNrM2VN
        NFQ1bE5OVk1tOUc5TFZEM1JGak1ObmhYNncwCjZScUs4YVNBa3UzQloxeTVuc0dU
        R2hIK2Zjai8vY3ZFM2hIUzZwNVVSRU0KLS0tIDY0dXQ0SG5JWUUvaVk5U0Qrd21n
        d1R3ZTN0aEdoeXl6OVAxWHdPSm9VVkkKiMTqeQ165hQyStJtCac1T4gBjZP013+N
        OlD7muZGDyHneakGIGWpIiDeIqwy6sZeFqr0p1pwu4iECqnJETojkw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1z6d3zhnz20zftekvmeuvygfjwsssua7tgtu00tt24uksvkpl9qdqr9ljqe
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-26T23:00:23Z"
  mac: ENC[AES256_GCM,data:S/dofV7bUVdA39NYvW3QnnE68he1qraxS8Z54jRPBYtW1XB4pTIgc5wpG/9BqmfDuuxgwOYTttfVJwJz/+h/TkMggmQepdZ/FBGLzA7M4ZXobqHaOg89UuHlvF4ljF7D14wHVNCBEgnjcIQl6QRb/8URhu7D6yhUu7XTQ4tZ2Vc=,iv:e7WWAwffsMmYXGK5bU2UgYfs6p5CXX2H6OjIEsk/um8=,tag:j1+xsUQDiYigmmOq2Tg5Vw==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
