---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./bundle.yaml
  - ./certificate.yaml
  - ./cluster.yaml
  - ./objectstore.yaml
  - ./grafana-db-secret.sops.yaml
  - ./scheduledbackup.yaml
  - ./secret.sops.yaml
  - ./service.yaml
