apiVersion: v1
kind: Secret
metadata:
  name: house-db-backup-creds
type: Opaque
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:xgvTZ02HSDub8AuodMZFHTkxa+lw2Mt8bQ==,iv:dXNNkCCtkIBCCgYNNqeu6McKQsV4dK6PuAWS5iVC2PE=,tag:bAbsUZlr1NSfsQcZUuNJrw==,type:str]
  ACCESS_SECRET_KEY: ENC[AES256_GCM,data:y7Ik5pj+u0zh5/OgvIKIjC2nAR75ph11+T2bvsc77g==,iv:RzClB4mqtrT8Xrr99zD5duLfprVq16HwTE3DM+U5rI0=,tag:sPn7urBo7GFRR1PbZLkHig==,type:str]
sops:
  age:
    - recipient: age1z6d3zhnz20zftekvmeuvygfjwsssua7tgtu00tt24uksvkpl9qdqr9ljqe
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2SDVFVmI2TjlLVTY0Q2JX
        TVZUNnUxeFN3Wk9FZXZ4WG1CeCtmNXYzeG04CmNEeHU1dkJrcXVHUGRtZXIzM3Nw
        QmxHcEtPN2xSMmEyZFFEVnVXUmRwYmcKLS0tIDFBcTVJSEQxYmV0VXpReEFrdXA2
        Ty9UZGZjVkVMeENXN0Z2SlA3SjRmZWsKmb3KP+5CFjaX2WRvqy3fDY6TmrFp+HaF
        BeOJIUfNkR3dTk26WNZ/+/b6UDngLa4KAT4RUkGY53HT0/xUC8yLzA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-07-11T00:43:35Z"
  mac: ENC[AES256_GCM,data:9A6YWZZ+JDBjgd5B50DB9IkvLlT/nsV5FsQWTEqNaGZlNd3xict+BW26dsh/o0EOvth5BlMc8ACHgjVOtG6+YS5bLjLP1afj7fqEMW702V89KF4NvZNs9+i7UsGEbj/ssx0k/we4sudLp9cSCfajSqPvPvjK3HDIqMda47wubgk=,iv:qzu0sn0Hl+QDpmcEqYXxRfJ8Mk9VPrLV3GkPbM0aX8A=,tag:7KJR/hK7MY0Bdq+fVDWKQw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
