apiVersion: apps/v1
kind: Deployment
metadata:
  name: piper
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: piper
  template:
    metadata:
      labels:
        app: piper
    spec:
      containers:
        - name: piper
          image: rhasspy/wyoming-piper:2.3.1@sha256:69b7f797ae3a8c3c0202cbf97152fb795d78c2355de2a31655c20671247360d8
          args: ["--voice", "en-us-lessac-low"]
          ports:
            - containerPort: 10200
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          ephemeral:
            volumeClaimTemplate:
              spec:
                accessModes: ["ReadWriteOnce"]
                resources:
                  requests:
                    storage: 1Gi
                storageClassName: openebs-hostpath