apiVersion: apps/v1
kind: Deployment
metadata:
  name: piper
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: piper
  template:
    metadata:
      labels:
        app: piper
    spec:
      containers:
        - name: piper
          image: rhasspy/wyoming-piper:2.5.2@sha256:7d39aafac409c2b6b09d999ed04d84c311d632e558b35baa60fad6aac722af7a
          args: ["--voice", "en-us-lessac-low"]
          ports:
            - containerPort: 10200
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          ephemeral:
            volumeClaimTemplate:
              spec:
                accessModes: ["ReadWriteOnce"]
                resources:
                  requests:
                    storage: 1Gi
                storageClassName: openebs-hostpath