---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app homeassistant
  namespace: &namespace default
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  
  components:
    - ../../../components/volsync
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  dependsOn:
    - name: openebs
      namespace: kube-system
  interval: 1h
  path: apps/default/homeassistant
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
    substitute:
      CLAIM: hass-config
      CAPACITY: 5Gi
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: false