---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
components:
  - ../../components/common
resources:
  - ./cilium/ks.yaml
#  - ./coredns/ks.yaml
#  - ./metrics-server/ks.yaml
  - ./openebs/ks.yaml
  - ./snapshot-controller/ks.yaml
#  - ./reloader/ks.yaml
#  - ./spegel/ks.yaml
patches:
  - target:
      kind: Namespace
      name: not-used
    patch: |-
      - op: add
        path: /metadata/labels
        values: {"topolvm.io/webhook": "ignore"}
  
