---
ingress:
  - hostname: "${SECRET_DOMAIN}"
    service: https://cilium-gateway-external.kube-system.svc.cluster.local
    originRequest:
      originServerName: "${SECRET_DOMAIN}"
      httpHostHeader: "${SECRET_DOMAIN}"
  - hostname: "*.${SECRET_DOMAIN:=example.com}"
    service: https://cilium-gateway-external.kube-system.svc.cluster.local
    originRequest:
      originServerName: "external.${SECRET_DOMAIN:=example.com}"
  - service: http_status:404