---
originRequest:
  originServerName: "external.${SECRET_DOMAIN:=example.com}"

ingress:
  - hostname: "${SECRET_DOMAIN}"
    service: &svc https://cilium-gateway-external.kube-system.svc.cluster.local
  - hostname: "*.${SECRET_DOMAIN:=example.com}"
    service: *svc
  - service: http_status:404