---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
   # renovate: datasource=github-releases depName=dignajar/another-autoscaler
 - https://raw.githubusercontent.com/dignajar/another-autoscaler/0.7/kubernetes/full.yaml
  