---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: &namespace network
components:
  - ../../components/common
resources:
  - ./cloudflare-dns/ks.yaml
  - ./cloudflare-tunnel/ks.yaml
  #- ./k8s-gateway/ks.yaml
  - ./multus/ks.yaml
patches:
  - target:
      kind: Namespace
      name: *namespace
    # todo: move hass to a different namespace, then remove privileged from default
    patch: |-
      - op: add
        path: /metadata/labels
        values: {"pod-security.kubernetes.io/enforce": "privileged"}
