---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: jupyter
spec:
  interval: 1h
  url: https://jupyterhub.github.io/helm-chart
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jupyter
spec:
  interval: 1h
  chart:
    spec:
      chart: jupyterhub
      version: 4.2.0
      sourceRef:  
        kind: HelmRepository
        name: jupyter
  install:
    remediation:
      retries: -1
  dependsOn:
    - name: openebs
      namespace: kube-system
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    debug:
      enabled: true
    hub:
      db:
        pvc:
          storageClassName: openebs-hostpath
    #    type: other
    #    url: sqlite:///jupyterhub.sqlite
    #  extraVolumeMounts:
    #    - mountPath: /srv/jupyterhub
    #      name: jupyterhub
    #      subPath: db
    #  extraVolumes:
    #    - name: jupyterhub
    #      persistentVolumeClaim:
    #        claimName: jupyterhub
    prePuller:
      continuous:
        enabled: false
    proxy:
      service:
        type: ClusterIP
    scheduling:
      userScheduler:
        enabled: false
    singleuser:
      storage:
        #type: static
        type: dynamic
        dynamic:
          storageClass: openebs-hostpath
        static:
          pvcName: jupyterhub
          subPath: "u/{username}"
          
          
  
     
  