---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
components:
  - ../../components/common
resources:
  - ./another-autoscaler/ks.yaml
  - ./esphome/ks.yaml
  - ./factorio/ks.yaml
  - ./homeassistant/ks.yaml
  - ./mosquitto/ks.yaml
  - ./openwakeword/ks.yaml
  - ./piper/ks.yaml
  - ./rtlamr/ks.yaml
  - ./whisper/ks.yaml
  - ./zigbee/ks.yaml