apiVersion: apps/v1
kind: Deployment
metadata:
  name: factorio
  namespace: default
  annotations:
    reloader.stakater.com/auto: "true"
    another-autoscaler/start-time: "30 0 * * 4"
    another-autoscaler/stop-time: "30 3 * * 4"
spec:
  #replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: factorio
  template:
    metadata:
      labels:
        app: factorio
    spec:
      nodeSelector:
        kubernetes.io/arch: "amd64"
      # todo: implement priority class
      # priorityClassName: high-priority
      containers:
        - name: factorio
          image: factoriotools/factorio:stable@sha256:c0e1a34c0f4704e51876772f5ea6a0ba1b399d7086bb1b990a1730a15fb0542a
          imagePullPolicy: Always
          ports:
            - containerPort: 34197
              type: UDP
              name: game
            - containerPort: 27015
              type: TCP
              name: rcon
          envFrom:
            - configMapRef:
                name: factorio-config
            - secretRef:
                name: factorio-secrets
          resources:
            requests:
              cpu: "4"
              memory: "8Gi"
            limits:
              cpu: "4"
              memory: "8Gi"
          volumeMounts:
            - name: factorio
              mountPath: /factorio
      volumes:
        - name: factorio
          persistentVolumeClaim:
            claimName: factorio
