apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: factorio-data
  namespace: default
spec:
  storageClassName: openebs-hostpath
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce