apiVersion: v1
kind: Secret
metadata:
  name: factorio-secrets
  namespace: default
type: Opaque
stringData:
  USERNAME: ENC[AES256_GCM,data:pvnG,iv:o9jAMO8HSexyORbZqyJ07KH4CYzgM5cftN/izvoUCYI=,tag:oxukf44YpFiJUX+MC6aJQg==,type:str]
  TOKEN: ENC[AES256_GCM,data:2IPDmgTm/4yT2+NxucVmbmOKwoCxSXzMnNX01gMx,iv:QzW//cEXAVdN96LZm5m09JCOiw+TRO2ZoyDs0ObyLns=,tag:iWyv7fuk3wmiiV2aL8BEYA==,type:str]
sops:
  age:
    - recipient: age1z6d3zhnz20zftekvmeuvygfjwsssua7tgtu00tt24uksvkpl9qdqr9ljqe
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBva3pHZ0hlbU1hdmUvRnZ5
        aEZVTDdWOXRBMFA0Y3JZMUdKMnFnTXIxRlVVCnVTei9WaDZyangyVjNTb1lPbElX
        TGFwTUxNWDh2U3VGcTZLdnFXTW1sYWMKLS0tIEM1M1E4K1RiRTE1Wnp1WDAvNjha
        WVhWUDM4M0poM0hreVozbU94dTJFeUkK+tbDJz4gchJrHPeUPZaGC7D7nP9ch5MJ
        0blBXakbn3Lt6gd7drYNq1fGDQNSxRcCH7RtOh9Aj67vcgciTBvmgg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-06T18:59:40Z"
  mac: ENC[AES256_GCM,data:9fUpHnvMawxvdjIRnvmg4ungKRbX91lLxCUlffdS39P2G9OKrnaUj+2Ib2On/8fLR1oubxo+wIO8mNA7yBeG+sy6CnK0/trIWQPmdYiYVWiKHSmcnBIO6oAKn+wWPhVbS48KKeoy/XGN2n4TsJpUaixklemrYfy88avU5fj96kM=,iv:DRa1Zhs0E6iks8+ocv2V2V396AziSna4IJYB9A4CHsc=,tag:Mf+e7+zQGOMNW2wHiYXMGg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
