# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel-secret
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:UvzH8KDtCvHEYTwO6fxDSWc7QurJgk1XbCMPqIJ9ymK8+Fg5lDmx+nP4jnw=,iv:Lg80PIDNqggchDYdyje0JgXOLfFCxGLI5Mleb7E3+Io=,tag:WTBPRZrsbj185K2mDmJyMQ==,type:str]
sops:
    age:
        - recipient: age1z6d3zhnz20zftekvmeuvygfjwsssua7tgtu00tt24uksvkpl9qdqr9ljqe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5WFpTOFc0Z3U1eDJtQW9T
            Rm9ncDZreVJSQ3AreXJDdVNLSStTc0lseURzCkFBNmRmZ0FMTWdhOHNXVHBYN3Na
            MDFDN3hvNnBFbEZudnFwV2NCSW82LzgKLS0tIDVFRW5mOEsrazFsRTJLeExFZjhu
            TDg0NmorNHUrekdsMk84ZVpZc0IyOWMKJZJs8D1s8bDv32zqFx0vnlcY3/RUiI6U
            VblFQliM7NHtng3Y5hbSZUSYEi4FtLBotq/OvK46SkejNakdwuwPmA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-06T01:03:19Z"
    mac: ENC[AES256_GCM,data:vct/W6Rh3B7hcdngY6KO+PRtQImEf6nxuVuRmtMcBndYouTbXZK/oO8+J4DdFvwKsgYmGwiKbGEDfoeyGrz4K819MiJqSAOReIL1VooloRBl9NvDoiaxb6xdd7v45E5xWFlSXSuWuz1vD6YH88UhjdHoO0N8V/1IqIxiUGJp3RI=,iv:bjBAmYNFJCkHwvDIlo4JEtzy7K8KmfaLSQX9I0tZlRk=,tag:c2zO8F5cORciWIKzNVueDw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.10.2
