# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:Ks/PrFVfCw84OPg7UC97DCtJn0ns1DbRvZ1B48iHC3BlNHxnZ65PbcO3Zg==,iv:grhaejGoCub/kd2b1lipplyxGODDtiLMLtCxQ92UTfA=,tag:DZyUhIY+CTEYJb+1hLGnBQ==,type:str]
sops:
  age:
    - recipient: age1z6d3zhnz20zftekvmeuvygfjwsssua7tgtu00tt24uksvkpl9qdqr9ljqe
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5WFpTOFc0Z3U1eDJtQW9T
        Rm9ncDZreVJSQ3AreXJDdVNLSStTc0lseURzCkFBNmRmZ0FMTWdhOHNXVHBYN3Na
        MDFDN3hvNnBFbEZudnFwV2NCSW82LzgKLS0tIDVFRW5mOEsrazFsRTJLeExFZjhu
        TDg0NmorNHUrekdsMk84ZVpZc0IyOWMKJZJs8D1s8bDv32zqFx0vnlcY3/RUiI6U
        VblFQliM7NHtng3Y5hbSZUSYEi4FtLBotq/OvK46SkejNakdwuwPmA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-04T19:45:33Z"
  mac: ENC[AES256_GCM,data:1BHnWS6UGfUHUDcmUhF+I6ns7g7GAKyVBBxId8gv1AaKmr7HKDruiPm1iiBEbrBVik17scZmGVGZFqDJK9VBicsfAEZuF09pfE+6a6OpeYkhmRgX0q+tjYjZ2yZSTmSe8dckvOS6nVhc0PCbr+stPQi8q2/Hk14pnDNmPOrHMBk=,iv:xH5vXA3g3APvy4OI9BsYeZU5YrjjzxINC6kal5ps0yk=,tag:CzwH1D7h3/B48x5KUbpkPg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
