cluster:
  allowSchedulingOnControlPlanes: true
  apiServer:
    extraArgs:
      # https://kubernetes.io/docs/tasks/extend-kubernetes/configure-aggregation-layer/
      # aggregator-routing is required when not using kube-proxy
      enable-aggregator-routing: true
  controllerManager:
    extraArgs:
      bind-address: 0.0.0.0
  # we install coreDNS from a helm chart, don't need talos's built in one
  coreDNS:
    disabled: true
  etcd:
    extraArgs:
      listen-metrics-urls: http://0.0.0.0:2381
    advertisedSubnets:
      - 192.168.1.0/24
  # cillium handles what kube-proxy would do
  proxy:
    disabled: true
  scheduler:
    extraArgs:
      bind-address: 0.0.0.0