alloy:
  enabled: false
engines:
  local:
    lvm:
      enabled: false
    zfs:
      enabled: true
  replicated:
    mayastor:
      enabled: false
  mayastor:
    crds:
      csi:
        volumeSnapshots:
          enabled: false
    csi:
      node:
        initContainers:
          enabled: false
zfs-localpv:
  zfsNode:
    encrKeysDir: /var/openebs/keys
  crds:
    csi:
      volumeSnapshots:
        enabled: false
localpv-provisioner:
  localpv:
    enabled: true
    basePath: /var/mnt/openebs/local

loki:
  enabled: false
  
  