---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: topolvm
  namespace: kube-system # Required for Renovate lookups
spec:
  interval: 1h
  url: https://topolvm.github.io/topolvm
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: topolvm
spec:
  interval: 1h
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
  chart:
    spec:
      chart: topolvm
      version: 15.5.6
      sourceRef:
        kind: HelmRepository
        name: topolvm
        namespace: kube-system
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    scheduler:
      enabled: false
    lvmd:
      deviceClasses:
        - name: ssd
          volume-group: myvg1
          default: true
          spare-gb: 10
        - name: "thin"
          volume-group: "myvg1"
          type: thin
          thin-pool:
            name: "pool0"
            overprovision-ratio: 5.0
    controller:
      replicaCount: 1
    storageClasses:
    - name: topolvm-provisioner  # Defines name of storage class.
      storageClass:
        fsType: ext4
        reclaimPolicy:  # Delete
        annotations: {}
        isDefaultClass: false
        volumeBindingMode: WaitForFirstConsumer
        allowVolumeExpansion: true
        additionalParameters: {}
        mountOptions: []
    - name: topolvm-provisioner-thin
      storageClass:
        fsType: ext4
        isDefaultClass: false
        volumeBindingMode: WaitForFirstConsumer
        allowVolumeExpansion: true
        additionalParameters:
          '{{ include "topolvm.pluginName" . }}/device-class': "thin"